print('Hoeveel mag de croissant kosten?')
a = (input())
print('Hoeveel croissantjes wilt u?')
b = (input())
print('Wat moet het stokbrood kosten?')
c = (input())
print('Hoeveel stokbroden wilt u?')
d = (input())
print('Wat zijn de kostingsbonnen waard?')
e = (input())
print('hoeveel kortingsbonnen heeft u?')
f = (input())
print('De eindprijs is', (float(a)*float(b)) + (float(c)*float(d)) - (float(e)*float(f)))