print('Met hoeveel mensen bent u?')
a = (input())
print('Wat kosten de tickets?')
b = (input())
print('Hoeveel tickets heeft u nodig?')
c = (input())
print('Hoeveel kost de VIP-VR-Gameseat per rit?')
d = (input())
print('Hoeveel keer wilt u in de VIP-VR-Gameseat?')
e = (input())
print('De dag kostte in totaal', (float(a)*float(b)) + (float(c)/float(d)*float(e)))

